line-length = 120
target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
	"W191",   # Indentation contains tabs
	"D212",   # Multi-line docstring summary should start at the first line
	"ANN101", # Missing type annotation for {name} in method
	"TD003",  # Missing issue link on the line following this TODO
	"INP001", # File {filename} is part of an implicit namespace package. Add an __init__.py.
	"D100",   # Missing docstring in public module
]
unfixable = [
	"F401", # {name} imported but unused; consider using importlib.util.find_spec to test for availability
	"F841", # Local variable {name} is assigned to but never used
	"B007", # Loop control variable {name} not used within loop body
]

[format]
indent-style = "tab"
